"""Добавил связи в сохраненное сообщение

Revision ID: 4242ef50f778
Revises: 22c47efee66a
Create Date: 2025-03-31 14:55:52.331248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4242ef50f778'
down_revision: Union[str, None] = '22c47efee66a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
