"""add city, street, house_number to listings

Revision ID: 6a90f7fe49aa
Revises: c855458e4739
Create Date: 2025-03-23 23:19:30.808506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a90f7fe49aa'
down_revision: Union[str, None] = 'c855458e4739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('city', sa.String(), nullable=True))
    op.add_column('listings', sa.Column('street', sa.String(), nullable=True))
    op.add_column('listings', sa.Column('house_number', sa.String(), nullable=True))
    op.add_column('listings', sa.Column('apartment_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'apartment_number')
    op.drop_column('listings', 'house_number')
    op.drop_column('listings', 'street')
    op.drop_column('listings', 'city')
    # ### end Alembic commands ###
