"""добавил isRead в Message

Revision ID: c70b40b3549a
Revises: 6a758a0fd781
Create Date: 2025-04-18 17:02:42.192442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c70b40b3549a'
down_revision: Union[str, None] = '6a758a0fd781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('isRead', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'isRead')
    # ### end Alembic commands ###
